// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['frontend']['GuiApp']['GetAppInfo']();
}

export function GetAutostartEnabled() {
  return window['go']['frontend']['GuiApp']['GetAutostartEnabled']();
}

export function GetEnterNonce(arg1) {
  return window['go']['frontend']['GuiApp']['GetEnterNonce'](arg1);
}

export function HideToTray() {
  return window['go']['frontend']['GuiApp']['HideToTray']();
}

export function OpenConfigFile() {
  return window['go']['frontend']['GuiApp']['OpenConfigFile']();
}

export function ResizeToMain() {
  return window['go']['frontend']['GuiApp']['ResizeToMain']();
}

export function SetAutostartEnabled(arg1) {
  return window['go']['frontend']['GuiApp']['SetAutostartEnabled'](arg1);
}

export function SetPorts(arg1, arg2) {
  return window['go']['frontend']['GuiApp']['SetPorts'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['frontend']['GuiApp']['ShowWindow']();
}

export function ValidateConfigKey(arg1, arg2) {
  return window['go']['frontend']['GuiApp']['ValidateConfigKey'](arg1, arg2);
}
