// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function GetAppInfo():Promise<frontend.AppInfo>;

export function GetAutostartEnabled():Promise<boolean>;

export function GetEnterNonce(arg1:boolean):Promise<string>;

export function HideToTray():Promise<void>;

export function OpenConfigFile():Promise<string>;

export function ResizeToMain():Promise<void>;

export function SetAutostartEnabled(arg1:boolean):Promise<void>;

export function SetPorts(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function ValidateConfigKey(arg1:string,arg2:boolean):Promise<string>;
