// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GuiApp Wails 绑定结构体。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppInfo 返回应用运行信息（含端口冲突检测）。
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1303911513).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetEnterNonce 生成一次性 nonce，用于 /gui/enter 安全跳转。
 */
export function GetEnterNonce(remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(3832583147, remember);
}

/**
 * OpenConfigFile 打开系统文件选择对话框，返回用户选择的配置文件路径。
 * 用户取消时返回空字符串。
 */
export function OpenConfigFile(): $CancellablePromise<string> {
    return $Call.ByID(1547608438);
}

/**
 * ResizeToMain 将登录窗口扩展为主界面尺寸。
 */
export function ResizeToMain(): $CancellablePromise<void> {
    return $Call.ByID(1128121742);
}

/**
 * SetPorts 更新端口配置并检测冲突。
 */
export function SetPorts(httpPort: string, subStorePort: string): $CancellablePromise<void> {
    return $Call.ByID(3443572318, httpPort, subStorePort);
}

/**
 * ValidateConfigKey 验证密钥，通过后返回一次性 nonce。
 */
export function ValidateConfigKey(enteredKey: string, remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(2798811533, enteredKey, remember);
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
