// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GuiApp Wails 绑定结构体。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BackToLogin 从 WebUI 返回登录窗口（可选功能，供托盘菜单使用）
 */
export function BackToLogin(): $CancellablePromise<void> {
    return $Call.ByID(2210097929);
}

/**
 * CompleteInit 在用户修正端口冲突后，由前端调用，完成后端初始化。
 */
export function CompleteInit(): $CancellablePromise<void> {
    return $Call.ByID(3843184923);
}

/**
 * EnterWebUI 由前端调用：导航 WebUI 窗口、显示它、隐藏登录窗口。
 * 完全无定时器，无闪烁。
 */
export function EnterWebUI(enterURL: string): $CancellablePromise<void> {
    return $Call.ByID(551937120, enterURL);
}

/**
 * GetAppInfo 返回应用运行信息（含端口冲突检测）。
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1303911513).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAutoStartEnabled 查询当前开机自启状态（供托盘菜单调用）。
 */
export function GetAutoStartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2283529356);
}

/**
 * GetEnterNonce 生成一次性 nonce，用于 /gui/enter 安全跳转。
 */
export function GetEnterNonce(remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(3832583147, remember);
}

/**
 * HideToTray 供前端"关闭按钮对话框"选择最小化时调用。
 */
export function HideToTray(): $CancellablePromise<void> {
    return $Call.ByID(171980759);
}

/**
 * OpenBrandURL 在 Wails 无地址栏窗口中打开品牌 / 社交链接。
 * 前端品牌面板（GitHub、Telegram、Docker Hub）及版本标签点击时调用，
 * 替代 window.open，避免打开系统默认浏览器，保持应用内体验一致。
 */
export function OpenBrandURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(541730476, url);
}

/**
 * OpenConfigFile 打开系统文件选择对话框，返回用户选择的配置文件路径。
 * 用户取消时返回空字符串（不返回错误）。
 */
export function OpenConfigFile(): $CancellablePromise<string> {
    return $Call.ByID(1547608438);
}

/**
 * QuitApp 供前端"关闭按钮对话框"选择退出时调用。
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(1033637092);
}

/**
 * ResizeToMain 将登录小窗无闪烁地切换为管理界面大窗。
 * 
 * 实现策略（Wails v3 原生方式）：
 *  1. 标记进入 WebUI 模式（关闭按钮改走 Go 原生对话框）
 *  2. 立即隐藏窗口（用户看不到后续的尺寸/导航变化）
 *  3. 调整窗口大小并居中
 *  4. 启动定时器，在外部页面加载完成后再显示窗口
 * 
 * 前端在此函数返回后立即执行 window.location.replace()，
 * 定时器在导航和页面渲染完成后触发 Show()，实现无感切换。
 */
export function ResizeToMain(): $CancellablePromise<void> {
    return $Call.ByID(1128121742);
}

/**
 * SetAutoStart 供前端 JS 绑定调用，切换开机自启。
 * 成功后同步更新托盘菜单 checkbox，保证两侧状态一致。
 */
export function SetAutoStart(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(940964243, enable);
}

/**
 * SetAutoStartEnabled 设置开机自启状态（供托盘菜单内部调用，不重复更新托盘 checkbox）。
 */
export function SetAutoStartEnabled(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(197427528, enable);
}

/**
 * SetPorts 更新端口配置。
 */
export function SetPorts(httpPort: string, subStorePort: string): $CancellablePromise<void> {
    return $Call.ByID(3443572318, httpPort, subStorePort);
}

/**
 * ShowWindow 供前端主动调用，显示并聚焦主窗口。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(91192051);
}

/**
 * ValidateConfigKey 验证密钥，通过后返回一次性 nonce。
 */
export function ValidateConfigKey(enteredKey: string, remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(2798811533, enteredKey, remember);
}

/**
 * ValidatePort 实时验证单个端口号合法性。
 */
export function ValidatePort(port: string): $CancellablePromise<string> {
    return $Call.ByID(2902552419, port);
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
