// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GuiApp Wails 绑定结构体。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BackToLogin 从 WebUI 返回登录窗口（可选功能，供托盘菜单使用）
 */
export function BackToLogin(): $CancellablePromise<void> {
    return $Call.ByID(2210097929);
}

/**
 * CheckForUpdates 触发更新检查，在 Wails 更新窗口中展示结果。
 * 供前端按钮和托盘菜单调用。
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(1256446317);
}

/**
 * CompleteInit 在用户修正端口冲突后，由前端调用，完成后端初始化。
 */
export function CompleteInit(): $CancellablePromise<void> {
    return $Call.ByID(3843184923);
}

/**
 * EnterWebUI 由前端调用：切换到本地 WebUI 大窗，隐藏登录小窗。
 * 
 * 迁移后不再需要传入 Gin 的 enterURL：
 *   - webUIWin 直接加载 Wails 资产服务器上的 /webui/admin.html
 *   - APIKey 和端口由 admin.html 内联脚本通过 Wails binding 自行获取
 */
export function EnterWebUI(): $CancellablePromise<void> {
    return $Call.ByID(551937120);
}

/**
 * GetApiKey 返回当前配置的 API Key，供本地 WebUI 页面通过 Wails binding 调用。
 * 
 * 安全边界：该 binding 仅对 Wails 资产服务器提供的页面可见（/webui/admin.html），
 * 外部网络无法调用。APIKey 本身已明文保存在 config.yaml，此处不增加额外泄露面。
 */
export function GetApiKey(): $CancellablePromise<string> {
    return $Call.ByID(242902589);
}

/**
 * GetAppInfo 返回应用运行信息（含端口冲突检测）。
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1303911513).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAutoStartEnabled 查询当前开机自启状态（供托盘菜单调用）。
 */
export function GetAutoStartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2283529356);
}

/**
 * GetEnterNonce 生成一次性 nonce，用于 /gui/enter 安全跳转。
 */
export function GetEnterNonce(remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(3832583147, remember);
}

/**
 * GetListenPort 返回 Gin HTTP 服务监听的端口号（不含冒号），
 * 供 newCombinedAssetHandler 构造反向代理目标地址使用。
 */
export function GetListenPort(): $CancellablePromise<string> {
    return $Call.ByID(96953646);
}

/**
 * GetUpdateInfo 向 GitHub API 查询最新 Release，返回更新状态给前端。
 * 
 * 使用场景：
 *   - AboutApp.tsx「检查更新」按钮 → 在「关于」窗口内内联展示更新结果，风格与整体 UI 一致
 *   - 不依赖 Wails 内置 updater 窗口，可完全自定义展示样式
 * 
 * 下载 URL 自动附加 https://ghproxy.net/ 前缀，改善中国大陆下载速度。
 */
export function GetUpdateInfo(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(1712625151).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * HideToTray 供前端"关闭按钮对话框"选择最小化时调用。
 */
export function HideToTray(): $CancellablePromise<void> {
    return $Call.ByID(171980759);
}

/**
 * IsBackendReady 动态查询后端是否已成功初始化并正在运行。
 * 
 * 与启动时快照的静态布尔值 appInitOK 不同，此方法读取 pendingInit 字段：
 * 端口冲突场景下 appInitOK==false，CompleteInit() 成功后 pendingInit 置 false，
 * 此方法立即返回 true，供 OnShutdown 和托盘状态轮询使用。
 */
export function IsBackendReady(): $CancellablePromise<boolean> {
    return $Call.ByID(4055968029);
}

/**
 * OpenAboutWindow 打开或聚焦「关于」独立窗口（单例模式）。
 * 
 * 调用来源：
 *   - 系统托盘「关于」菜单项（tray.go）
 *   - 主窗口前端「关于」按钮（about-info-btn）
 * 
 * 使用 application.InvokeAsync 确保所有窗口操作在 Wails 主线程执行，
 * 避免从 Go binding 调用线程直接操作 UI 导致的竞态问题。
 */
export function OpenAboutWindow(): $CancellablePromise<void> {
    return $Call.ByID(3115421951);
}

/**
 * OpenBrandURL 在 Wails 无地址栏窗口中打开品牌 / 社交链接。
 * 前端品牌面板（GitHub、Telegram、Docker Hub）及版本标签点击时调用，
 * 替代 window.open，避免打开系统默认浏览器，保持应用内体验一致。
 */
export function OpenBrandURL(url: string, windowSize: string): $CancellablePromise<void> {
    return $Call.ByID(541730476, url, windowSize);
}

/**
 * OpenConfigFile 打开系统文件选择对话框，返回用户选择的配置文件路径。
 * 用户取消时返回空字符串（不返回错误）。
 */
export function OpenConfigFile(): $CancellablePromise<string> {
    return $Call.ByID(1547608438);
}

/**
 * OpenInternalPage 在新窗口中打开内置 Web 页面（如 /files、/analysis）。
 * 
 * 设计要点：
 *   - 所有内置页面均通过 /gui/enter?n=<nonce>&redirect=<path> 中转，
 *     确保新弹出窗口的 sessionStorage 写入正确的 API Key，与打开 admin 一致。
 *   - 窗口先加载本地 loading.html（立即显示，无白屏），300 ms 后由 Go 端通过
 *     SetURL 发起外部导航——规避 JS 跨 origin 导航拦截。
 */
export function OpenInternalPage(path: string, title: string, windowSize: string): $CancellablePromise<void> {
    return $Call.ByID(1633695184, path, title, windowSize);
}

/**
 * OpenSubLinksWindow 打开或聚焦「订阅链接」独立窗口（单例模式）。
 * 
 * 调用来源：
 *   - 主窗口前端快捷按钮区「订阅链接」按钮（KeySection）
 * 
 * 窗口加载 Vite MPA 入口 /sub-links.html，前端自行通过
 * Wails 资产代理（/api/...）拉取订阅数据并展示。
 */
export function OpenSubLinksWindow(): $CancellablePromise<void> {
    return $Call.ByID(4239119837);
}

/**
 * OpenSubStoreUI 在弹出窗口中打开 Sub-Store 订阅管理页面。
 * 
 * 设计要点：
 *   - 若 config.yaml 配置了 sub-store-path，自动拼接 ?api=<path>，
 *     让 Sub-Store 前端直接完成后端绑定，无需用户手动输入。
 *   - 窗口先加载本地 loading.html（立即显示，无白屏），300 ms 后由 Go 端通过
 *     SetURL 发起外部导航——规避 Wails3 WKWebView/WebView2 对 JS 跨 origin
 *     导航的拦截，确保最终页面能正确加载。
 *   - 不依赖 JS window.location / window.open，无 WebKit 弹窗拦截问题。
 */
export function OpenSubStoreUI(): $CancellablePromise<void> {
    return $Call.ByID(3080875275);
}

/**
 * QuitApp 供前端"关闭按钮对话框"选择退出时调用。
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(1033637092);
}

/**
 * ResizeToMain 将登录小窗无闪烁地切换为管理界面大窗。
 * 
 * 实现策略（Wails v3 原生方式）：
 *  1. 标记进入 WebUI 模式（关闭按钮改走 Go 原生对话框）
 *  2. 立即隐藏窗口（用户看不到后续的尺寸/导航变化）
 *  3. 调整窗口大小并居中
 *  4. 启动定时器，在外部页面加载完成后再显示窗口
 * 
 * 前端在此函数返回后立即执行 window.location.replace()，
 * 定时器在导航和页面渲染完成后触发 Show()，实现无感切换。
 */
export function ResizeToMain(): $CancellablePromise<void> {
    return $Call.ByID(1128121742);
}

/**
 * SetAutoStart 供前端 JS 绑定调用，切换开机自启。
 * 成功后同步更新托盘菜单 checkbox，保证两侧状态一致。
 */
export function SetAutoStart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(940964243, enabled);
}

/**
 * SetAutoStartEnabled 设置开机自启状态（供托盘菜单内部调用，不重复更新托盘 checkbox）。
 */
export function SetAutoStartEnabled(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(197427528, enable);
}

/**
 * SetPorts 更新端口配置。
 */
export function SetPorts(httpPort: string, subStorePort: string): $CancellablePromise<void> {
    return $Call.ByID(3443572318, httpPort, subStorePort);
}

/**
 * ShowWindow 供前端主动调用，显示并聚焦主窗口。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(91192051);
}

/**
 * ValidateConfigKey 验证密钥，通过后返回一次性 nonce。
 */
export function ValidateConfigKey(enteredKey: string, remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(2798811533, enteredKey, remember);
}

/**
 * ValidatePort 实时验证单个端口号合法性（格式 + 是否被占用）。
 * 返回空字符串表示端口格式正确且当前未被占用。
 */
export function ValidatePort(port: string): $CancellablePromise<string> {
    return $Call.ByID(2902552419, port);
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
