// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfo 前端展示所需的应用运行信息。
 */
export class AppInfo {
    "apiKey": string;
    "listenPort": string;
    "subStorePort": string;

    /**
     * KeyIsRandom 为 true 表示 api-key 随机生成（重启后变更）
     */
    "keyIsRandom": boolean;

    /**
     * IsFirstRun 为 true 表示本次是首次运行
     */
    "isFirstRun": boolean;

    /**
     * ConfigPath config.yaml 的实际路径
     */
    "configPath": string;

    /**
     * PortConflictHTTP 为 true 表示 HTTP 端口被占用
     */
    "portConflictHTTP": boolean;

    /**
     * PortConflictSubStore 为 true 表示 Sub-Store 端口被占用
     */
    "portConflictSubStore": boolean;

    /**
     * AutostartEnabled 当前平台开机自启状态
     */
    "autostartEnabled": boolean;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("listenPort" in $$source)) {
            this["listenPort"] = "";
        }
        if (!("subStorePort" in $$source)) {
            this["subStorePort"] = "";
        }
        if (!("keyIsRandom" in $$source)) {
            this["keyIsRandom"] = false;
        }
        if (!("isFirstRun" in $$source)) {
            this["isFirstRun"] = false;
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("portConflictHTTP" in $$source)) {
            this["portConflictHTTP"] = false;
        }
        if (!("portConflictSubStore" in $$source)) {
            this["portConflictSubStore"] = false;
        }
        if (!("autostartEnabled" in $$source)) {
            this["autostartEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}
