// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfo 前端展示所需的应用运行信息。
 */
export class AppInfo {
    "apiKey": string;
    "listenPort": string;
    "subStorePort": string;

    /**
     * SubStorePath Sub-Store 后端 API 路径（config.yaml 中的 sub-store-path）。
     */
    "subStorePath": string;

    /**
     * KeyIsRandom 为 true 表示 api-key 随机生成（重启后变更）
     */
    "keyIsRandom": boolean;

    /**
     * IsFirstRun 为 true 表示本次是首次运行
     */
    "isFirstRun": boolean;

    /**
     * ConfigPath config.yaml 的实际路径
     */
    "configPath": string;

    /**
     * PortConflictHTTP 为 true 表示 HTTP 端口被占用
     */
    "portConflictHTTP": boolean;

    /**
     * PortConflictSubStore 为 true 表示 Sub-Store 端口被占用
     */
    "portConflictSubStore": boolean;

    /**
     * PendingInit 为 true 表示后端尚未初始化，需要前端先解决端口冲突
     */
    "pendingInit": boolean;

    /**
     * AutostartEnabled 当前平台开机自启状态
     */
    "autostartEnabled": boolean;

    /**
     * GuiVersion 桌面客户端版本（ldflags 注入，如 "v1.2.0"）
     */
    "guiVersion": string;

    /**
     * CoreVersion 内核版本+短提交哈希（如 "v2.5.4@7c23868"）
     */
    "coreVersion": string;

    /**
     * OriginVersion 内核版本
     */
    "originVersion": string;

    /**
     * LocalIPs 本机所有可用局域网 IPv4 地址（不含回环），供订阅链接窗口切换访问地址。
     */
    "localIPs": string[];

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("listenPort" in $$source)) {
            this["listenPort"] = "";
        }
        if (!("subStorePort" in $$source)) {
            this["subStorePort"] = "";
        }
        if (!("subStorePath" in $$source)) {
            this["subStorePath"] = "";
        }
        if (!("keyIsRandom" in $$source)) {
            this["keyIsRandom"] = false;
        }
        if (!("isFirstRun" in $$source)) {
            this["isFirstRun"] = false;
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("portConflictHTTP" in $$source)) {
            this["portConflictHTTP"] = false;
        }
        if (!("portConflictSubStore" in $$source)) {
            this["portConflictSubStore"] = false;
        }
        if (!("pendingInit" in $$source)) {
            this["pendingInit"] = false;
        }
        if (!("autostartEnabled" in $$source)) {
            this["autostartEnabled"] = false;
        }
        if (!("guiVersion" in $$source)) {
            this["guiVersion"] = "";
        }
        if (!("coreVersion" in $$source)) {
            this["coreVersion"] = "";
        }
        if (!("originVersion" in $$source)) {
            this["originVersion"] = "";
        }
        if (!("localIPs" in $$source)) {
            this["localIPs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localIPs" in $$parsedSource) {
            $$parsedSource["localIPs"] = $$createField14_0($$parsedSource["localIPs"]);
        }
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

/**
 * UpdateInfo 前端展示更新状态所需的结构体。
 */
export class UpdateInfo {
    "hasUpdate": boolean;
    "latestVersion": string;
    "currentVersion": string;
    "releaseNotes": string;
    "downloadURL": string;
    "error": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
