// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UpdateStatus {
    "available": boolean;
    "version": string;

    /** Creates a new UpdateStatus instance. */
    constructor($$source: Partial<UpdateStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus($$parsedSource as Partial<UpdateStatus>);
    }
}
